[    { "surah": "Al-Fatihah", "ruku": 1, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 2, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 3, "ayat_count": 13 },
    { "surah": "Al-Baqarah", "ruku": 4, "ayat_count": 9 },
    { "surah": "Al-Baqarah", "ruku": 5, "ayat_count": 10 },
    { "surah": "Al-Baqarah", "ruku": 6, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 7, "ayat_count": 13 },
    { "surah": "Al-Baqarah", "ruku": 8, "ayat_count": 2 },
    { "surah": "Al-Baqarah", "ruku": 9, "ayat_count": 12 },
    { "surah": "Al-Baqarah", "ruku": 10, "ayat_count": 4 },
    { "surah": "Al-Baqarah", "ruku": 11, "ayat_count": 4 },
    { "surah": "Al-Baqarah", "ruku": 12, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 13, "ayat_count": 5 },
    { "surah": "Al-Baqarah", "ruku": 14, "ayat_count": 8 },
    { "surah": "Al-Baqarah", "ruku": 15, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 16, "ayat_count": 8 },
    { "surah": "Al-Baqarah", "ruku": 17, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 18, "ayat_count": 15 },
    { "surah": "Al-Baqarah", "ruku": 19, "ayat_count": 11 },
    { "surah": "Al-Baqarah", "ruku": 20, "ayat_count": 4 },
    { "surah": "Al-Baqarah", "ruku": 21, "ayat_count": 6 },
    { "surah": "Al-Baqarah", "ruku": 22, "ayat_count": 6 },
    { "surah": "Al-Baqarah", "ruku": 23, "ayat_count": 6 },
    { "surah": "Al-Baqarah", "ruku": 24, "ayat_count": 8 },
    { "surah": "Al-Baqarah", "ruku": 25, "ayat_count": 14 },
    { "surah": "Al-Baqarah", "ruku": 26, "ayat_count": 6 },
    { "surah": "Al-Baqarah", "ruku": 27, "ayat_count": 5 },
    { "surah": "Al-Baqarah", "ruku": 28, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 29, "ayat_count": 3 },
    { "surah": "Al-Baqarah", "ruku": 30, "ayat_count": 4 },
    { "surah": "Al-Baqarah", "ruku": 31, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 32, "ayat_count": 6 },
    { "surah": "Al-Baqarah", "ruku": 33, "ayat_count": 5 },
    { "surah": "Al-Baqarah", "ruku": 34, "ayat_count": 4 },
    { "surah": "Al-Baqarah", "ruku": 35, "ayat_count": 3 },
    { "surah": "Al-Baqarah", "ruku": 36, "ayat_count": 6 },
    { "surah": "Al-Baqarah", "ruku": 37, "ayat_count": 7 },
    { "surah": "Al-Baqarah", "ruku": 38, "ayat_count": 8 },
    { "surah": "Al-Baqarah", "ruku": 39, "ayat_count": 2 },
    { "surah": "Al-Baqarah", "ruku": 40, "ayat_count": 3 },
    { "surah": "Ali 'Imran", "ruku": 41, "ayat_count": 9 },
    { "surah": "Ali 'Imran", "ruku": 42, "ayat_count": 11 },
    { "surah": "Ali 'Imran", "ruku": 43, "ayat_count": 10 },
    { "surah": "Ali 'Imran", "ruku": 44, "ayat_count": 11 },
    { "surah": "Ali 'Imran", "ruku": 45, "ayat_count": 13 },
    { "surah": "Ali 'Imran", "ruku": 46, "ayat_count": 8 },
    { "surah": "Ali 'Imran", "ruku": 47, "ayat_count": 9 },
    { "surah": "Ali 'Imran", "ruku": 48, "ayat_count": 9 },
    { "surah": "Ali 'Imran", "ruku": 49, "ayat_count": 11 },
    { "surah": "Ali 'Imran", "ruku": 50, "ayat_count": 10 },
    { "surah": "Ali 'Imran", "ruku": 51, "ayat_count": 8 },
    { "surah": "Ali 'Imran", "ruku": 52, "ayat_count": 11 },
    { "surah": "Ali 'Imran", "ruku": 53, "ayat_count": 9 },
    { "surah": "Ali 'Imran", "ruku": 54, "ayat_count": 14 },
    { "surah": "Ali 'Imran", "ruku": 55, "ayat_count": 5 },
    { "surah": "Ali 'Imran", "ruku": 56, "ayat_count": 7 },
    { "surah": "Ali 'Imran", "ruku": 57, "ayat_count": 16 },
    { "surah": "Ali 'Imran", "ruku": 58, "ayat_count": 16 },
    { "surah": "Ali 'Imran", "ruku": 59, "ayat_count": 9 },
    { "surah": "Ali 'Imran", "ruku": 60, "ayat_count": 10 },
    { "surah": "Ali 'Imran", "ruku": 61, "ayat_count": 10 },
    { "surah": "Ali 'Imran", "ruku": 62, "ayat_count": 11 },
    { "surah": "Ali 'Imran", "ruku": 63, "ayat_count": 8 },
    { "surah": "Ali 'Imran", "ruku": 64, "ayat_count": 16 },
    { "surah": "Al-Nisa", "ruku": 65, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 66, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 67, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 68, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 69, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 70, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 71, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 72, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 73, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 74, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 75, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 76, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 77, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 78, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 79, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 80, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 81, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 82, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 83, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 84, "ayat_count": 7 },
    { "surah": "Al-Nisa", "ruku": 85, "ayat_count": 7 },
    { "surah": "Al-Ma'idah", "ruku": 86, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 87, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 88, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 89, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 90, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 91, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 92, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 93, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 94, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 95, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 96, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 97, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 98, "ayat_count": 6 },
    { "surah": "Al-Ma'idah", "ruku": 99, "ayat_count": 6 },
    { "surah": "Al-A'raf", "ruku": 122, "ayat_count": 9 },
    { "surah": "An-Nazi'at", "ruku": 333, "ayat_count": 26 },
    { "surah": "An-Nazi'at", "ruku": 334, "ayat_count": 20 },
    { "surah": "Abasa", "ruku": 335, "ayat_count": 42 },
    { "surah": "At-Takwir", "ruku": 336, "ayat_count": 29 },
    { "surah": "Al-Infitar", "ruku": 337, "ayat_count": 19 },
    { "surah": "Al-Mutaffifin", "ruku": 338, "ayat_count": 36 },
    { "surah": "Al-Inshiqaq", "ruku": 339, "ayat_count": 25 },
    { "surah": "Al-Buruj", "ruku": 340, "ayat_count": 22 },
    { "surah": "At-Tariq", "ruku": 341, "ayat_count": 17 },
    { "surah": "Al-A'la", "ruku": 342, "ayat_count": 19 },
    { "surah": "Al-Ghashiyah", "ruku": 343, "ayat_count": 26 },
    { "surah": "Al-Fajr", "ruku": 344, "ayat_count": 30 },
    { "surah": "Al-Balad", "ruku": 345, "ayat_count": 20 },
    { "surah": "Ash-Shams", "ruku": 346, "ayat_count": 15 },
    { "surah": "Al-Lail", "ruku": 347, "ayat_count": 21 },
    { "surah": "Ad-Duha", "ruku": 348, "ayat_count": 11 },
    { "surah": "Al-Inshirah", "ruku": 349, "ayat_count": 8 },
    { "surah": "At-Tin", "ruku": 350, "ayat_count": 8 },
    { "surah": "Al-'Alaq", "ruku": 351, "ayat_count": 19 },
    { "surah": "Al-Qadr", "ruku": 352, "ayat_count": 5 },
    { "surah": "Al-Bayyinah", "ruku": 353, "ayat_count": 8 },
    { "surah": "Az-Zilzal", "ruku": 354, "ayat_count": 8 },
    { "surah": "Al-Adiyat", "ruku": 355, "ayat_count": 11 },
    { "surah": "Al-Qari'ah", "ruku": 356, "ayat_count": 11 },
    { "surah": "At-Takathur", "ruku": 357, "ayat_count": 8 },
    { "surah": "Al-'Asr", "ruku": 358, "ayat_count": 3 },
    { "surah": "Al-Humazah", "ruku": 359, "ayat_count": 9 },
    { "surah": "Al-Fil", "ruku": 360, "ayat_count": 5 },
    { "surah": "Quraysh", "ruku": 361, "ayat_count": 4 },
    { "surah": "Al-Ma'un", "ruku": 362, "ayat_count": 7 },
    { "surah": "Al-Kawthar", "ruku": 363, "ayat_count": 3 },
    { "surah": "Al-Kafirun", "ruku": 364, "ayat_count": 6 },
    { "surah": "An-Nasr", "ruku": 365, "ayat_count": 3 },
    { "surah": "Al-Masad", "ruku": 366, "ayat_count": 5 },
    { "surah": "Al-Ikhlas", "ruku": 367, "ayat_count": 4 },
    { "surah": "Al-Falaq", "ruku": 368, "ayat_count": 5 },
    { "surah": "An-Nas", "ruku": 369, "ayat_count": 6 }
  ]
  