<script>
  import { onMount } from 'svelte';
  import { SveltePlayer } from '../../../lib/Player';
  import Deckbuilder from "../../../lib/deckbuilder/Deckbuilder";

  /* 📥  Local deck file generated by DeckBuilder.build() */
  /*     (Place it in the same folder and export “default deckObj”) */
  import {defineDeck} from './theorems9old_11.1.2';

  /* Player props */
   const deckbuilder = new Deckbuilder();
  defineDeck(deckbuilder);
  const question = deckbuilder.build();
  const deck = question.deck;

  const background = question.background ?? {}; // fallback if author omitted
  let   soundUrl   = '';                      // no audio in work desk preview
  let   mounted    = false;

  onMount(() => { mounted = true; });
</script>

{#if mounted}
  <SveltePlayer
    {deck}
    {background}
    {soundUrl}
  />
{/if}

<style>
  /* center “Loading” if JS is slow */
  .flex           { display: flex; }
  .items-center   { align-items: center; }
  .justify-center { justify-content: center; }
  .h-full         { height: 100%; }
</style>
